export enum GameState {
  IN_PROGRESS,
  WHITE_IN_CHECK,
  BLACK_IN_CHECK,
  WHITE_WON,
  BLACK_WON,
  WHITE_WON_BY_SURRENDER,
  BLACK_WON_BY_SURRENDER,
  DRAW_STALEMATE,
  DRAW_INSUFFICIENT_MATERIAL,
  DRAW_THREEFOLD_REPETITION,
}
