name: Build & Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build & Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: sisimomo/hexagonal-chess-frontend:latest , sisimomo/hexagonal-chess-frontend:${{ github.event.release.tag_name }}

  deploy_to_vm:
    name: Deploy to VM
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/deployments/hexagonalChess/prod
            docker pull sisimomo/hexagonal-chess-frontend:latest
            docker compose up -d --force-recreate hexagonalChess_frontend
